# Generated by Django 3.1.4 on 2020-12-02 11:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointsOrder',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=7, null=True)),
                ('id_shape', models.FloatField(blank=True, null=True)),
                ('id_part', models.FloatField(blank=True, null=True)),
                ('id_point', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'points_order',
                'managed': False,
            },
        ),
    ]
