# Generated by Django 3.1.4 on 2020-12-09 08:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Att456',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('ele', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=20, null=True)),
                ('sym', models.CharField(blank=True, max_length=20, null=True)),
                ('hdop', models.FloatField(blank=True, null=True)),
                ('locus_icon', models.CharField(blank=True, max_length=20, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'att_4_56',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riverdata',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('id_shape', models.FloatField(blank=True, null=True)),
                ('id_part', models.FloatField(blank=True, null=True)),
                ('id_point', models.FloatField(blank=True, null=True)),
                ('id_pk', models.CharField(blank=True, max_length=10, null=True)),
                ('plastic', models.IntegerField(blank=True, db_column='Plastic', null=True)),
            ],
            options={
                'db_table': 'riverData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='datepicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
