# Generated by Django 3.1.4 on 2020-12-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0002_att456_datepicker_riverdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datepicker',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datepicker',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
