# Generated by Django 3.1.4 on 2020-12-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0006_hotspots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotspots',
        ),
    ]
